apiVersion: apps/v1
kind: Deployment
metadata:
  name: facade-deploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: facade-api
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: facade-api
    spec:
      containers:
      - name: facadeapi
        image: starwarstoodmerkacr.azurecr.io/facadeapi:latest
        ports:
          - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: star-wars-svc
  labels:
    app: facade-api
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: facade-api

